spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/tracker
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 20
        enable_lazy_load_no_trans: true
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc:
          batch_size: 20
        cache:
          use_second_level_cache: true

---

spring:
  profiles: inmem
  datasource:
    url: jdbc:h2:mem:tracker
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 20
        enable_lazy_load_no_trans: true
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
        cache:
          use_second_level_cache: true

  h2:
    console:
      enabled: true