version: '2.2'
services:
  pg_tracker:
    image: postgres
    container_name: pg_tracker
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tracker
    networks:
      trackerNetwork:
        ipv4_address: 172.18.1.1

  tracker:
    image: voroby/tracker_openjdk
    container_name: tracker
    ports:
      - 8080:8080
    networks:
      trackerNetwork:
        ipv4_address: 172.18.1.2

networks:
  trackerNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1